# Generated by t_compile from base.html
import t_tmpl

def html(title, **_kw):
  _, _q, _emit = t_tmpl._ctx("attr")
  _emit(u'<html>\n<head>\n')
  dot = title
  _emit('<title>')
  _emit(_q(title))
  _emit(u'</title>\n</head>\n<body>\n\tHello from base\n</body>\n</html>')
  return _.result()
